export type Release = {
  title: string;
  guid: string;
  detailsUrl?: string;
  downloadUrl?: string;
  indexer: string;
  category?: string;
  size?: number;
  age?: number;
  grabs?: number;
  seeders?: number;
  publishDate?: string;
  imdbId?: string;
  tmdbId?: string;
  tvdbId?: string;
  season?: number;
  episode?: number;
  resolution?: string;
  source?: string;
  codec?: string;
  audio?: string;
  hdr: boolean;
  dv: boolean;
  language?: string;
  releaseGroup?: string;
  isRepack: boolean;
  isProper: boolean;
  isRemux: boolean;
  rawAttributes: Record<string, unknown>;
};
